name: Recognitions Statistics

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Check if commit is by GitHub Actions
      run: |
        echo "Commit author: ${{ github.event.head_commit.author.username }}"
      id: check_commit_author

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install requests matplotlib  # Add other dependencies as needed

    - name: Run Python Script
      run: python ./statistics/statistics-recognitions.py

    - name: Check for changes
      id: check_changes
      if: ${{ steps.check_commit_author.outputs.commit_author != 'github-actions' }}
      run: |
        if ! git diff --quiet; then
          git config --local user.name  ${{ github.actor }}
          git config --local user.email "<>"
          git add .
          git commit -m "Recognitions Statistics"
          echo "::set-output name=changes::true"
        else
          echo "No changes to commit."
          echo "::set-output name=changes::false"
        fi

    - name: Push changes  # push the generated files to your repo
      if: ${{ steps.check_changes.outputs.changes == 'true' }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true
